import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'title': 'Hello Word',
      'The world in brief': 'The world in brief',
      'Top stories': 'Top stories',
      'Finance & economics': 'Finance & economics',
      'What happened to the artificial-intelligence revolution?': 'What happened to the artificial-intelligence revolution?',
      'So far the technology has had almost no economic impact': 'So far the technology has had almost no economic impact',
      '7 min read': '7 min read',
      'Leaders': 'Leaders',
      "Big tech's capex splurge may be irrationally exuberant": "Big tech's capex splurge may be irrationally exuberant",
      '4 min read': '4 min read',
      'Translate to English': 'Translate to English',
      'Translate to Urdu': 'Translate to Urdu',
      'Translate to Hindi': 'Translate to Hindi',
      'date': 'June 29th 2024',
      'play_audio': 'Play audio',
      'build_queue': 'Build queue',
      'download_edition': 'Download edition',
      'world_this_week': 'The world this week',
      'category': 'Politics',
      'read_time': '5 min read',
      'Podcasts': 'Podcasts',
      'TRAILER': 'TRAILER',
      'Boom!': 'Boom!',
      'Our new series finds out how the generation born in the era of the bomb blew up American politics. Launching July 2024.':
      'Our new series finds out how the generation born in the era of the bomb blew up American politics. Launching July 2024.',
      'Latest episodes': 'Latest episodes',
      'The Intelligence': 'The Intelligence',
      'Degree programme: stopping heat deaths': 'Degree programme: stopping heat deaths',
      '22:13': '22:13',
      'Daily and weekly': 'Daily and weekly',
      'Item': 'Item',
      'Babbage': 'Babbage',
      'Learn about the latest innovations and discoveries in science and technology':
      'Learn about the latest innovations and discoveries in science and technology',
      'Favourite': 'Favourite',
      'Asia': 'Asia',
      'Takashima Ryosuke is \n Japan\'s youngest ever mayor': 'Takashima Ryosuke is \n Japan\'s youngest ever mayor',
      'Jul 3rd 2024': 'Jul 3rd 2024',
      '5 min read': '5 min read',
      'JOIN US ON SOCIAL MEDIA' : 'JOIN US ON SOCIAL MEDIA',
      'For even more \n exclusive content!': 'For even more \n exclusive content!',
      "Home": "Home",
      "Weekly": "Weekly",
      "Podcasts": "Podcasts",
      "Favourite": "Favourite",
      "Translate": "Translate",
      "General": "General",
      "Entertainment": "Entertainment",
      "Health": "Health",
      "Sports": "Sports",
      "Business": "Business",
      "Technology": "Technology"

    },
    'ur_PK': {
      'title': 'ہیلو ورڈ',
      'The world in brief': 'دنیا مختصر میں',
      'Top stories': 'اہم خبریں',
      'Finance & economics': 'مالیات اور معیشت',
      'What happened to the artificial-intelligence revolution?': 'مصنوعی ذہانت کے انقلاب کو کیا ہوا؟',
      'So far the technology has had almost no economic impact': 'اب تک اس ٹیکنالوجی کا تقریباً کوئی معاشی اثر نہیں ہوا',
      '7 min read': '7 منٹ پڑھیں',
      'Leaders': 'رہنما',
      "Big tech's capex splurge may be irrationally exuberant": "بڑی ٹیک کا سرمایہ خرچ کرنا غیر ضروری ہو سکتا ہے",
      '4 min read': '4 منٹ پڑھیں',
      'Translate to English': 'انگریزی میں ترجمہ کریں',
      'Translate to Urdu': 'اردو میں ترجمہ کریں',
      'Translate to Hindi': 'ہندی میں ترجمہ کریں',
      'date': '29 جون 2024',
      'play_audio': 'آڈیو چلائیں',
      'build_queue': 'قطار بنائیں',
      'download_edition': 'ایڈیشن ڈاؤن لوڈ کریں',
      'world_this_week': 'اس ہفتے کی دنیا',
      'category': 'سیاست',
      'read_time': '5 منٹ پڑھیں',
      'Podcasts': 'پوڈکاسٹس',
      'TRAILER': 'ٹریلر',
      'Boom!': 'بوم!',
      'Our new series finds out how the generation born in the era of the bomb blew up American politics. Launching July 2024.':
      'ہمارا نیا سلسلہ یہ جاننے کے لیے ہے کہ بم کے دور میں پیدا ہونے والی نسل نے امریکی سیاست کو کیسے اڑا دیا۔ جولائی 2024 سے لانچ ہو رہا ہے۔',
      'Latest episodes': 'تازہ ترین اقساط',
      'The Intelligence': 'انٹیلی جنس',
      'Degree programme: stopping heat deaths': 'ڈگری پروگرام: گرمی سے موت کو روکنا',
      '22:13': '22:13',
      'Daily and weekly': 'روزانہ اور ہفتہ وار',
      'Item': 'آئٹم',
      'Babbage': 'بیباج',
      'Learn about the latest innovations and discoveries in science and technology':
      'سائنس اور ٹیکنالوجی میں تازہ ترین جدتوں اور دریافتوں کے بارے میں جانیں',
      'Favourite': 'پسندیدہ',
      'Asia': 'ایشیاء',
      'Takashima Ryosuke is \n Japan\'s youngest ever mayor': 'تکاشیما ریوسکی سب سے کم عمر میئر ہے',
      'Jul 3rd 2024': '3 جولائی 2024',
      '5 min read': '5 منٹ پڑھائی',
      'JOIN US ON SOCIAL MEDIA':'سوشل میڈیا پر ہمارے ساتھ شامل ہوں',
      'For even more \n exclusive content!': 'اس سے بھی زیادہ \n خصوصی مواد کے لیے!',
      "Home": "ہوم",
      "Weekly": "ہفتہ وار",
      "Podcasts": "پوڈکاسٹس",
      "Favourite": "پسندیدہ",
      "Translate": "ترجمہ",
      "General": "عام",
      "Entertainment": "تفریح",
      "Health": "صحت",
      "Sports": "کھیل",
      "Business": "کاروبار",
      "Technology": "ٹیکنالوجی"
    },
    'hi_IN': {
      'title': 'हैलो वर्ड',
      'The world in brief': 'संक्षेप में दुनिया',
      'Top stories': 'मुख्य समाचार',
      'Finance & economics': 'वित्त और अर्थशास्त्र',
      'What happened to the artificial-intelligence revolution?': 'कृत्रिम-बुद्धिमत्ता क्रांति को क्या हुआ?',
      'So far the technology has had almost no economic impact': 'अब तक इस तकनीक का लगभग कोई आर्थिक प्रभाव नहीं पड़ा है',
      '7 min read': '7 मिनट पढ़ें',
      'Leaders': 'नेता',
      "Big tech's capex splurge may be irrationally exuberant": "बड़ी तकनीक का पूंजी व्यय उत्साहवर्धक हो सकता है",
      '4 min read': '4 मिनट पढ़ें',
      'Translate to English': 'अंग्रेजी में अनुवाद करें',
      'Translate to Urdu': 'उर्दू में अनुवाद करें',
      'Translate to Hindi': 'हिंदी में अनुवाद करें',
      'date': '29 जून 2024',
      'play_audio': 'ऑडियो चलाएं',
      'build_queue': 'कतार बनाएं',
      'download_edition': 'संस्करण डाउनलोड करें',
      'world_this_week': 'इस सप्ताह की दुनिया',
      'category': 'राजनीति',
      'read_time': '5 मिनट पढ़ें',
      'Podcasts': 'पॉडकास्ट',
      'TRAILER': 'ट्रेलर',
      'Boom!': 'बूम!',
      'Our new series finds out how the generation born in the era of the bomb blew up American politics. Launching July 2024.':
      'हमारी नई श्रृंखला यह पता लगाती है कि बम के युग में पैदा हुई पीढ़ी ने अमेरिकी राजनीति को कैसे उड़ा दिया। जुलाई 2024 से लॉन्च हो रहा है।',
      'Latest episodes': 'नवीनतम एपिसोड',
      'The Intelligence': 'बुद्धिमत्ता',
      'Degree programme: stopping heat deaths': 'डिग्री कार्यक्रम: गर्मी से होने वाली मौतों को रोकना',
      '22:13': '22:13',
      'Daily and weekly': 'दैनिक और साप्ताहिक',
      'Item': 'आइटम',
      'Babbage': 'बैबेज',
      'Learn about the latest innovations and discoveries in science and technology':
      'विज्ञान और प्रौद्योगिकी में नवीनतम नवाचारों और खोजों के बारे में जानें',
      'Favourite': 'पसंदीदा',
      'Asia': 'एशिया',
      'Takashima Ryosuke is \n Japan\'s youngest ever mayor': 'ताकाशिमा र्योसुके सबसे कम उम्र के मेयर हैं',
      'Jul 3rd 2024': '3 जुलाई 2024',
      '5 min read': '5 मिनट पढ़ाई',
      'JOIN US ON SOCIAL MEDIA':'सोशल मीडिया पर हमसे जुड़ें',
      'For even more \n exclusive content!': 'और भी अधिक विशेष सामग्री के लिए!',
      "Home": "होम",
      "Weekly": "साप्ताहिक",
      "Podcasts": "पॉडकास्ट",
      "Favourite": "पसंदीदा",
      "Translate": "अनुवाद",
      "General": "सामान्य",
      "Entertainment": "मनोरंजन",
      "Health": "स्वास्थ्य",
      "Sports": "खेल",
      "Business": "व्यवसाय",
      "Technology": "प्रौद्योगिकी"
    },
  };
}
